### ISSUE TITLE
Images for README

### ISSUE THREAD

**Issue by R3DDY97** [R3DDY97/KICKthemOUT3#1]
![kicknew](https://cloud.githubusercontent.com/assets/13858661/24928497/3d759850-1f20-11e7-8703-00a704fd269d.png)

**Comment by R3DDY97** [comment]
![v2](https://cloud.githubusercontent.com/assets/13858661/25564001/b68cbd22-2dc6-11e7-9316-1343294835ea.png)

**Comment by ghost** [comment]
What commends???
